// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CalendarModuleScssNamespace {
    export interface ICalendarModuleScss {
        button: string;
        export: string;
        header: string;
        next: string;
        other: string;
        paper: string;
        previous: string;
        万年历: string;
        三胜宫header: string;
        三胜宫tab: string;
        中文: string;
        九天: string;
        值符: string;
        八字: string;
        公历: string;
        六十四卦名: string;
        六十四卦象: string;
        十二值神: string;
        喜气: string;
        地支: string;
        天干: string;
        干支: string;
        年: string;
        年月: string;
        建: string;
        开: string;
        成: string;
        执: string;
        拼音: string;
        方位: string;
        日: string;
        日历: string;
        星期: string;
        星期日: string;
        月: string;
        月历: string;
        生门: string;
        英文: string;
        语录: string;
    }
}

declare const CalendarModuleScssModule: CalendarModuleScssNamespace.ICalendarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CalendarModuleScssNamespace.ICalendarModuleScss;
};

export = CalendarModuleScssModule;
