// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CoreModuleScssNamespace {
    export interface ICoreModuleScss {
        btn: string;
        centertable: string;
        darkTheme: string;
        deleteAccountIcon: string;
        firebaseuiDialog: string;
        firebaseuiIdDialog: string;
        mdlDialog: string;
        muiSelectSelect: string;
        print: string;
        star: string;
        telegramLinkButton: string;
        telegramLoginButton: string;
        telegramLoginSupremeDivinityBot: string;
        text: string;
        tgmeWidgetLoginButton: string;
        tgmeWidgetLoginButtonIcon: string;
        tgmeWidgetLoginUserPhoto: string;
        userInfoLink: string;
        土: string;
        女icon: string;
        性键: string;
        性键字英: string;
        文件dialog: string;
        木: string;
        水: string;
        火: string;
        男icon: string;
        金: string;
    }
}

declare const CoreModuleScssModule: CoreModuleScssNamespace.ICoreModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CoreModuleScssNamespace.ICoreModuleScss;
};

export = CoreModuleScssModule;
