// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LoginModuleScssNamespace {
    export interface ILoginModuleScss {
        button: string;
        center: string;
        email: string;
        emailNew: string;
        icon: string;
        inputForm: string;
        login: string;
        loginButton: string;
        loginDialog: string;
        more: string;
        other: string;
        phone: string;
        provider: string;
        sms: string;
        w7rem: string;
        域: string;
        姓名: string;
    }
}

declare const LoginModuleScssModule: LoginModuleScssNamespace.ILoginModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LoginModuleScssNamespace.ILoginModuleScss;
};

export = LoginModuleScssModule;
