// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageModuleScssNamespace {
    export interface IPageModuleScss {
        breakBefore: string;
        center: string;
        copyright: string;
        coverBackground: string;
        coverFooter: string;
        end: string;
        flex: string;
        flex1: string;
        footer: string;
        footerSpace: string;
        footerText: string;
        header: string;
        headerText: string;
        height1: string;
        height100: string;
        logo: string;
        m12px: string;
        main: string;
        noBackground: string;
        page: string;
        pageCenter: string;
        pageOnly: string;
        paper: string;
        printOnly: string;
        red: string;
        screenOnly: string;
        textBase: string;
        w210mm: string;
        watermark: string;
        watermarkPaper: string;
        wfitContent: string;
        width100: string;
        widthPaper: string;
    }
}

declare const PageModuleScssModule: PageModuleScssNamespace.IPageModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PageModuleScssNamespace.IPageModuleScss;
};

export = PageModuleScssModule;
